version: "3.3"  # optional since v1.27.0
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
